### ISSUE TITLE
ipcompatibility with "Plain Text Links"

### ISSUE THREAD

**Issue by GiftWolf** [piroor/textlink#37]
Text Link stops working when the addon "Plain Text Links" (https://addons.mozilla.org/en-US/firefox/addon/plain-text-links/ ) is installed. I can't even open the options.

**Comment by piroor** [comment]
I've realized why they conflict with each other. The addon uses internal URLs like `chrome://textlink/content/...`, but it is just same to this Text Link's internal URLs.  I used the internal URL since 2004, so I think I have a prior right to use it and he should change Plain Text Link's internal URLs to unique one. 

http://piro.sakura.ne.jp/xul/textlink/index.html.en#focused-folding-item%28folding-item-history-1%29
https://addons.mozilla.org/en-US/firefox/addon/text-link/versions/?page=2
https://addons.mozilla.org/en-US/firefox/addon/plain-text-links/versions/

**Comment by piroor** [comment]
Outdated.
